// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAhDcLabOS64CBnqLe-aoY5m84w-4Teuw',
    appId: '1:323929920152:web:459173f8352189b64b36ed',
    messagingSenderId: '323929920152',
    projectId: 'renote-84312',
    authDomain: 'renote-84312.firebaseapp.com',
    storageBucket: 'renote-84312.appspot.com',
    measurementId: 'G-L9BPERXQXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRdI2doR2eTlmV-HgtoUzFkUjXCNRMMxI',
    appId: '1:323929920152:android:ade324d67695277f4b36ed',
    messagingSenderId: '323929920152',
    projectId: 'renote-84312',
    storageBucket: 'renote-84312.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBgDpJoj2ZfKWh5p6l5ildRFp57Q2loh4',
    appId: '1:323929920152:ios:f963955d294dde054b36ed',
    messagingSenderId: '323929920152',
    projectId: 'renote-84312',
    storageBucket: 'renote-84312.appspot.com',
    iosBundleId: 'com.example.renote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBgDpJoj2ZfKWh5p6l5ildRFp57Q2loh4',
    appId: '1:323929920152:ios:ae805246447cafb84b36ed',
    messagingSenderId: '323929920152',
    projectId: 'renote-84312',
    storageBucket: 'renote-84312.appspot.com',
    iosBundleId: 'com.example.renote.RunnerTests',
  );
}
